@UI @SMK @PRD @CMP 
Feature: Product reusable component

  Background:
    Given the user is landed on the "LOGIN" page

  Scenario Outline: <TestID>: Verify product fields for different users
    And the user logs in with username "<username>" and password "STANDARD_PASSWORD"
    When the user is landed on the "PRODUCTS" page
    Then the product "<product>" should display correct <field> with value "<expected>"

    Examples:
      | TestID     | username      | product                           | field       | expected                                                                                                                                                               |
      | TC_SMK_008 | STANDARD_USER | Sauce Labs Backpack               | description | carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.                                 |
      | TC_SMK_009 | STANDARD_USER | Sauce Labs Backpack               | price       | $29.99                                                                                                                                                                 |
      | TC_SMK_010 | STANDARD_USER | Sauce Labs Backpack               | image       | /static/media/sauce-backpack-1200x1500.0a0b85a3.jpg                                                                                                                    |
      | TC_SMK_011 | STANDARD_USER | Sauce Labs Bike Light             | description | A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.        |
      | TC_SMK_012 | STANDARD_USER | Sauce Labs Bike Light             | price       | $9.99                                                                                                                                                                  |
      | TC_SMK_013 | STANDARD_USER | Sauce Labs Bike Light             | image       | /static/media/bike-light-1200x1500.37c843b0.jpg                                                                                                                        |
      | TC_SMK_014 | STANDARD_USER | Sauce Labs Fleece Jacket          | description | It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office. |
      | TC_SMK_015 | STANDARD_USER | Sauce Labs Fleece Jacket          | price       | $49.99                                                                                                                                                                 |
      | TC_SMK_016 | STANDARD_USER | Sauce Labs Fleece Jacket          | image       | /static/media/sauce-pullover-1200x1500.51d7ffaf.jpg                                                                                                                    |
      | TC_SMK_017 | STANDARD_USER | Sauce Labs Bolt T-Shirt           | description | Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.                        |
      | TC_SMK_018 | STANDARD_USER | Sauce Labs Bolt T-Shirt           | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_019 | STANDARD_USER | Sauce Labs Bolt T-Shirt           | image       | /static/media/bolt-shirt-1200x1500.c2599ac5.jpg                                                                                                                        |
      | TC_SMK_020 | STANDARD_USER | Sauce Labs Onesie                 | description | Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.        |
      | TC_SMK_021 | STANDARD_USER | Sauce Labs Onesie                 | price       | $7.99                                                                                                                                                                  |
      | TC_SMK_022 | STANDARD_USER | Sauce Labs Onesie                 | image       | /static/media/red-onesie-1200x1500.2ec615b2.jpg                                                                                                                        |
      | TC_SMK_023 | STANDARD_USER | Test.allTheThings() T-Shirt (Red) | description | This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.              |
      | TC_SMK_024 | STANDARD_USER | Test.allTheThings() T-Shirt (Red) | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_025 | STANDARD_USER | Test.allTheThings() T-Shirt (Red) | image       | /static/media/red-tatt-1200x1500.30dadef4.jpg                                                                                                                          |
      | TC_SMK_026 | PROBLEM_USER  | Sauce Labs Backpack               | description | carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.                                 |
      | TC_SMK_027 | PROBLEM_USER  | Sauce Labs Backpack               | price       | $29.99                                                                                                                                                                 |
      | TC_SMK_028 | PROBLEM_USER  | Sauce Labs Backpack               | image       | /static/media/sauce-backpack-1200x1500.0a0b85a3.jpg                                                                                                                    |
      | TC_SMK_029 | PROBLEM_USER  | Sauce Labs Bike Light             | description | A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.        |
      | TC_SMK_030 | PROBLEM_USER  | Sauce Labs Bike Light             | price       | $9.99                                                                                                                                                                  |
      | TC_SMK_031 | PROBLEM_USER  | Sauce Labs Bike Light             | image       | /static/media/bike-light-1200x1500.37c843b0.jpg                                                                                                                        |
      | TC_SMK_032 | PROBLEM_USER  | Sauce Labs Fleece Jacket          | description | It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office. |
      | TC_SMK_033 | PROBLEM_USER  | Sauce Labs Fleece Jacket          | price       | $49.99                                                                                                                                                                 |
      | TC_SMK_034 | PROBLEM_USER  | Sauce Labs Fleece Jacket          | image       | /static/media/sauce-pullover-1200x1500.51d7ffaf.jpg                                                                                                                    |
      | TC_SMK_035 | PROBLEM_USER  | Sauce Labs Bolt T-Shirt           | description | Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.                        |
      | TC_SMK_036 | PROBLEM_USER  | Sauce Labs Bolt T-Shirt           | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_037 | PROBLEM_USER  | Sauce Labs Bolt T-Shirt           | image       | /static/media/bolt-shirt-1200x1500.c2599ac5.jpg                                                                                                                        |
      | TC_SMK_038 | PROBLEM_USER  | Sauce Labs Onesie                 | description | Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.        |
      | TC_SMK_039 | PROBLEM_USER  | Sauce Labs Onesie                 | price       | $7.99                                                                                                                                                                  |
      | TC_SMK_040 | PROBLEM_USER  | Sauce Labs Onesie                 | image       | /static/media/red-onesie-1200x1500.2ec615b2.jpg                                                                                                                        |
      | TC_SMK_041 | PROBLEM_USER  | Test.allTheThings() T-Shirt (Red) | description | This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.              |
      | TC_SMK_042 | PROBLEM_USER  | Test.allTheThings() T-Shirt (Red) | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_043 | PROBLEM_USER  | Test.allTheThings() T-Shirt (Red) | image       | /static/media/red-tatt-1200x1500.30dadef4.jpg                                                                                                                          |
      | TC_SMK_044 | ERROR_USER    | Sauce Labs Backpack               | description | carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.                                 |
      | TC_SMK_045 | ERROR_USER    | Sauce Labs Backpack               | price       | $29.99                                                                                                                                                                 |
      | TC_SMK_046 | ERROR_USER    | Sauce Labs Backpack               | image       | /static/media/sauce-backpack-1200x1500.0a0b85a3.jpg                                                                                                                    |
      | TC_SMK_047 | ERROR_USER    | Sauce Labs Bike Light             | description | A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.        |
      | TC_SMK_048 | ERROR_USER    | Sauce Labs Bike Light             | price       | $9.99                                                                                                                                                                  |
      | TC_SMK_049 | ERROR_USER    | Sauce Labs Bike Light             | image       | /static/media/bike-light-1200x1500.37c843b0.jpg                                                                                                                        |
      | TC_SMK_050 | ERROR_USER    | Sauce Labs Fleece Jacket          | description | It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office. |
      | TC_SMK_051 | ERROR_USER    | Sauce Labs Fleece Jacket          | price       | $49.99                                                                                                                                                                 |
      | TC_SMK_052 | ERROR_USER    | Sauce Labs Fleece Jacket          | image       | /static/media/sauce-pullover-1200x1500.51d7ffaf.jpg                                                                                                                    |
      | TC_SMK_053 | ERROR_USER    | Sauce Labs Bolt T-Shirt           | description | Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.                        |
      | TC_SMK_054 | ERROR_USER    | Sauce Labs Bolt T-Shirt           | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_055 | ERROR_USER    | Sauce Labs Bolt T-Shirt           | image       | /static/media/bolt-shirt-1200x1500.c2599ac5.jpg                                                                                                                        |
      | TC_SMK_056 | ERROR_USER    | Sauce Labs Onesie                 | description | Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.        |
      | TC_SMK_057 | ERROR_USER    | Sauce Labs Onesie                 | price       | $7.99                                                                                                                                                                  |
      | TC_SMK_058 | ERROR_USER    | Sauce Labs Onesie                 | image       | /static/media/red-onesie-1200x1500.2ec615b2.jpg                                                                                                                        |
      | TC_SMK_059 | ERROR_USER    | Test.allTheThings() T-Shirt (Red) | description | This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.              |
      | TC_SMK_060 | ERROR_USER    | Test.allTheThings() T-Shirt (Red) | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_061 | ERROR_USER    | Test.allTheThings() T-Shirt (Red) | image       | /static/media/red-tatt-1200x1500.30dadef4.jpg                                                                                                                          |
      | TC_SMK_062 | VISUAL_USER   | Sauce Labs Backpack               | description | carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.                                 |
      | TC_SMK_063 | VISUAL_USER   | Sauce Labs Backpack               | price       | $29.99                                                                                                                                                                 |
      | TC_SMK_064 | VISUAL_USER   | Sauce Labs Backpack               | image       | /static/media/sauce-backpack-1200x1500.0a0b85a3.jpg                                                                                                                    |
      | TC_SMK_065 | VISUAL_USER   | Sauce Labs Bike Light             | description | A red light isn't the desired state in testing but it sure helps when riding your bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included.        |
      | TC_SMK_066 | VISUAL_USER   | Sauce Labs Bike Light             | price       | $9.99                                                                                                                                                                  |
      | TC_SMK_067 | VISUAL_USER   | Sauce Labs Bike Light             | image       | /static/media/bike-light-1200x1500.37c843b0.jpg                                                                                                                        |
      | TC_SMK_068 | VISUAL_USER   | Sauce Labs Fleece Jacket          | description | It's not every day that you come across a midweight quarter-zip fleece jacket capable of handling everything from a relaxing day outdoors to a busy day at the office. |
      | TC_SMK_069 | VISUAL_USER   | Sauce Labs Fleece Jacket          | price       | $49.99                                                                                                                                                                 |
      | TC_SMK_070 | VISUAL_USER   | Sauce Labs Fleece Jacket          | image       | /static/media/sauce-pullover-1200x1500.51d7ffaf.jpg                                                                                                                    |
      | TC_SMK_071 | VISUAL_USER   | Sauce Labs Bolt T-Shirt           | description | Get your testing superhero on with the Sauce Labs bolt T-shirt. From American Apparel, 100% ringspun combed cotton, heather gray with red bolt.                        |
      | TC_SMK_072 | VISUAL_USER   | Sauce Labs Bolt T-Shirt           | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_073 | VISUAL_USER   | Sauce Labs Bolt T-Shirt           | image       | /static/media/bolt-shirt-1200x1500.c2599ac5.jpg                                                                                                                        |
      | TC_SMK_074 | VISUAL_USER   | Sauce Labs Onesie                 | description | Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel.        |
      | TC_SMK_075 | VISUAL_USER   | Sauce Labs Onesie                 | price       | $7.99                                                                                                                                                                  |
      | TC_SMK_076 | VISUAL_USER   | Sauce Labs Onesie                 | image       | /static/media/red-onesie-1200x1500.2ec615b2.jpg                                                                                                                        |
      | TC_SMK_077 | VISUAL_USER   | Test.allTheThings() T-Shirt (Red) | description | This classic Sauce Labs t-shirt is perfect to wear when cozying up to your keyboard to automate a few tests. Super-soft and comfy ringspun combed cotton.              |
      | TC_SMK_078 | VISUAL_USER   | Test.allTheThings() T-Shirt (Red) | price       | $15.99                                                                                                                                                                 |
      | TC_SMK_079 | VISUAL_USER   | Test.allTheThings() T-Shirt (Red) | image       | /static/media/red-tatt-1200x1500.30dadef4.jpg                                                                                                                          |
