name: Run WDIO UI Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  wdio-ui-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run WDIO tests filtered by @UI
      - name: Run WDIO UI Tests
        run: npx wdio run wdio.conf.ts --cucumberOpts.tagExpression "@UI"

      # 5. Upload Allure results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # 6. Generate and upload Allure HTML report
      - name: Generate Allure Report
        if: always()
        run: npx allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

